config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # devise
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations', # edit_user_registration_path
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    unlocks:       'users/unlocks'
  }

  devise_for :admins, controllers: {
    confirmations: 'admins/confirmations',
    registrations: 'admins/registrations', # edit_admin_registration_path
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    unlocks:       'admins/unlocks'
  }
  
  # home
  get '/', to: 'homes#index', as: 'index_home'
  get 'homes/policy', to: 'homes#policy', as: 'policy_home'
  get 'homes/terms', to: 'homes#terms', as: 'terms_home'
  get 'homes/tokushoho', to: 'homes#tokushoho', as: 'tokushoho_home'
  get 'homes/how_to_use', to: 'homes#how_to_use', as: 'how_to_use_home'

  # post
  get 'posts/index', to: 'posts#index', as: 'index_post'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  post 'posts/new', to: 'posts#create', as: 'create_post'
  get 'posts/show/:post_id', to: 'posts#show', as: 'show_post'
  get 'posts/edit/:post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/edit/:post_id', to: 'posts#update', as: 'update_post'
  delete 'posts/destroy/:post_id', to: 'posts#destroy', as: 'destroy_post'

  # profile
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles/new', to: 'profiles#create', as: 'create_profile'
  get 'profiles/show/:user_id', to: 'profiles#show', as: 'show_profile'
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/edit', to: 'profiles#update', as: 'update_profile'

  # comment
  get 'posts/show/:post_id/comments/new/:id', to: 'comments#new', as: 'new_comment'
  post 'posts/show/:post_id/comments/new', to: 'comments#create', as: 'create_comment'
  get 'posts/show/:post_id/comments/new_reply/:comment_id', to: 'comments#new_reply', as: 'new_reply_comment'
  post 'posts/show/:post_id/comments/new_reply/:comment_id', to: 'comments#create_reply', as: 'create_reply_comment'
  get 'comments/relevant', to: 'comments#load_relevant_comments', as: 'load_relevant_comment'
  delete 'comments/destroy/:comment_id', to: 'comments#destroy', as: 'destroy_comment'

  # like  
  post 'posts/:post_id/likes', to: 'likes#create', as: 'create_like'
  delete 'posts/:post_id/likes', to: 'likes#destroy', as: 'destroy_like'
  get 'likes/show', to: 'likes#show', as: 'show_like'

  # subscription
  get 'subscriptions/top', to: 'subscriptions#top', as: 'top_subscription'
  get 'subscriptions/new', to: 'subscriptions#new', as: 'new_subscription'
  post 'subscriptions/create_stripe_customer', to: 'subscriptions#create_stripe_customer', as: 'create_stripe_customer'
  get 'subscriptions/create_customer_portal', to: 'subscriptions#create_customer_portal', as: 'create_customer_portal'
  get 'subscriptions/payment_cancel', to: 'subscriptions#payment_cancel', as: 'payment_cancel'
  get 'subscriptions/checkout_success', to: 'subscriptions#checkout_success', as: 'checkout_success'
  get 'subscriptions/loading', to: 'subscriptions#loading', as: 'loading_subscription'
  get '/subscription_status', to: 'subscriptions#subscription_status'

  # contact
  get 'contacts/new', to: 'contacts#new', as: 'new_contact'
  post 'contacts/new', to: 'contacts#create', as: 'create_contact'

  # stripe
  post '/webhooks', to: 'webhooks#create'
  post '/checkouts', to: 'checkouts#create'

  # admin
  # user
  get 'admins/users/index', to: 'admins/users#index', as: 'index_admin_user'
  get 'admins/users/edit/:user_id', to: 'admins/users#edit', as: 'edit_admin_user'
  post 'admins/users/edit/:user_id', to: 'admins/users#update', as: 'update_admin_user'
  delete 'admins/users/destroy/:user_id', to: 'admins/users#destroy', as: 'destroy_admin_user'

  # post
  get 'admins/posts/index', to: 'admins/posts#index', as: 'index_admin_post'
  get 'admins/posts/media_index', to: 'admins/posts#media_index', as: 'media_index_admin_post'
  post 'admins/posts/media_index/:post_id', to: 'admins/posts#compress_media', as: 'compress_media_admin_post'
  delete 'admins/posts/destroy/:post_id', to: 'admins/posts#destroy', as: 'destroy_admin_post'

  # profile
  get 'admins/profiles/index', to: 'admins/profiles#index', as: 'index_admin_profile'
  get 'admins/profiles/media_index', to: 'admins/profiles#media_index', as: 'media_index_admin_profile'
  post 'admins/profiles/media_index/:profile_id', to: 'admins/profiles#compress_media', as: 'compress_media_admin_profile'
  delete 'admins/profiles/destroy/:profile_id', to: 'admins/profiles#destroy', as: 'destroy_admin_profile'

  # comment
  get 'admins/comments/index', to: 'admins/comments#index', as: 'index_admin_comment'
  delete 'admins/comments/destroy/:comment_id', to: 'admins/comments#destroy', as: 'destroy_admin_comment'

  # subscription
  get 'admins/subscriptions/index', to: 'admins/subscriptions#index', as: 'index_admin_subscription'
  get 'admins/subscriptions/edit/:subscription_id', to: 'admins/subscriptions#edit', as: 'edit_admin_subscription'
  post 'admins/subscriptions/edit/:subscription_id', to: 'admins/subscriptions#update', as: 'update_admin_subscription'
  delete 'admins/subscriptions/destroy/:subscription_id', to: 'admins/subscriptions#destroy', as: 'destroy_admin_subscription'

  # dashboard
  get 'admins/dashboards/index', to: 'admins/dashboards#index', as: 'index_admin_dashboard'

  # analytics
  get 'admins/analytics/index', to: 'admins/analytics#index', as: 'index_admin_analytics'

  # Sidekiq Web UI
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_many :replies, class_name: "Comment", foreign_key: "parent_comment_id", dependent: :destroy
  belongs_to :parent_comment, class_name: "Comment", optional: true

  validates :content, presence: true
end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
    @comments = Comment.all
  end

	def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    redirect_to index_admin_comment_path, notice: '投稿を削除しました。'
  end

  private

  def authenticate_admin!
    unless current_user&.admin?
      redirect_to index_post_path, alert: '管理者のみがアクセスできます。'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :check_subscription_status

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @comments = Comment.where(post_id: params[:post_id])
    @comment_user_profiles = []
    @comments.each do |comment|
      comment_user_profile = Profile.find_by(user_id: comment.user_id)
      @comment_user_profiles << comment_user_profile
    end
    @profile = Profile.find_by(user_id: @post.user_id)
    @from = params[:id].to_i # 0:postにコメント可能 1:postにコメント不可
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to new_comment_path(params[:post_id], 0), notice: 'コメントしました'
      begin
        CommentMailer.receive_comment_mail(@comment).deliver_now
      rescue => e
        puts "An error occurred: #{e.message}"
      end
    else
      @post = Post.find(params[:post_id])
      @comments = Comment.where(post_id: params[:post_id])
      @comment_user_profiles = []
      @comments.each do |comment|
        comment_user_profile = Profile.find_by(user_id: comment.user_id)
        @comment_user_profiles << comment_user_profile
      end
      @profile = Profile.find_by(user_id: @post.user_id)
      render :new, status: :unprocessable_entity
    end
  end

  def new_reply
    @post = Post.find(params[:post_id])
    @profile = Profile.find_by(user_id: @post.user_id)
    @comment = Comment.new
    @comments = Comment.where(parent_comment_id: params[:comment_id])
    @comment_user_profiles = []
    @comments.each do |comment|
      comment_user_profile = Profile.find_by(user_id: comment.user_id)
      @comment_user_profiles << comment_user_profile
    end
    
    @parent_comment = Comment.find(params[:comment_id])
    @past_comments = []
    @past_comments << @parent_comment
    past_comment = @parent_comment
    while true
      if past_comment.parent_comment_id.nil?
        break
      else
        past_comment = Comment.find(past_comment.parent_comment_id)
        @past_comments << past_comment
      end
    end
    @past_comments.reverse!
    render :new_reply
  end

  def create_reply
    @comment = Comment.new(comment_params)
    @comment.parent_comment_id = params[:comment_id]
    if @comment.save
      redirect_to new_reply_comment_path(params[:post_id], @comment.id), notice: '返信しました'
      begin
        CommentMailer.receive_comment_mail(@comment).deliver_now
      rescue => e
        puts "An error occurred: #{e.message}"
      end
    else
      parent_comment = Comment.find(params[:comment_id])
      if parent_comment.parent_comment_id
        redirect_to new_reply_comment_path(params[:post_id], parent_comment.parent_comment_id), alert: '返信に失敗しました'
      else
        redirect_to new_comment_path(params[:post_id], 0), alert: '返信に失敗しました'
      end
    end
  end

  def load_relevant_comments
    # 投稿主が current_user の root コメント
    root_comments = Comment.joins(:post)
                          .where(parent_comment_id: nil, posts: { user_id: current_user.id })
    # current_user のコメントに対する返信
    reply_comments = Comment.where(parent_comment_id: Comment.where(user_id: current_user.id).select(:id))
    # 両方を　@comments　にまとめて作成日時の昇順で並び替え、最初の100件を取得
    @comments = (root_comments + reply_comments).sort_by(&:created_at).reverse.first(100)
    # ユーザーIDの一覧からまとめてProfileを取得（1クエリ）
    profiles = Profile.where(user_id: @comments.map(&:user_id).uniq).index_by(&:user_id)
    # コメントごとに対応するプロフィールを並べた配列を作成
    @comment_user_profiles = @comments.map { |comment| profiles[comment.user_id] }
    render :relevant
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    redirect_to show_profile_path(current_user.id), notice: 'コメントを削除しました'
  end


  private
  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id).merge(post_id: params[:post_id], user_id: current_user.id)
  end
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<div class="post-list">
  <div class="post">
    <div class="header">
      <div class="header_image">
        <% if @profile.image.attached? %>
          <%= link_to show_profile_path(@profile.user_id) do %>
            <%= image_tag(@profile.image) %>
          <% end %>
        <% else %>
          <%= link_to show_profile_path(@profile.user_id) do %>
            <%= image_tag 'no_image.png' %>
          <% end %>
        <% end %>
      </div>
      <h2 class="username"><%= @profile.nickname %></h2>
      <h2 class="category"><%= @post.category %></h2>
      <h2 class="timestamp">
        <% if Time.current - @post.created_at < 24.hours %>
          <%= @post.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
        <% else %>
          <%= @post.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
        <% end %>
      </h2>
    </div>
    <div class="body">
      <p class="content auto-change-url"><%= @post.body %></p>
    </div>
    <div class="media">
      <% if @post.media.attached? %>
        <% if @post.media.content_type.start_with?('image/') %>
          <%= image_tag(@post.media, alt: "Posted image", class: "img") %>
        <% elsif @post.media.content_type.start_with?('video/') %>
          <video controls class="video" poster="<%= url_for(@post.video_thumbnail) %>">
            <source src="<%= url_for(@post.media) %>" type="<%= @post.media.content_type %>">
            お使いのブラウザは動画タグをサポートしていません。
          </video>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% if @from == 0 %>
  <div class="comment-form-container">
    <div class="comment">
      <%= form_with(url: create_comment_path(@post), model: @comment, local: true, method: :post) do |f| %>

        <% if @comment.errors.any? %>
          <ul class="error-messages">
            <% @comment.errors.full_messages.each do |message| %>
              <li>・<%= message %></li>
            <% end %> </ul>
        <% end %>

        <div class="form">
          <div class="textarea">
            <%= f.label "コメント", class: 'form-label' %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>

          <div class="button-group">
            <%= f.submit '送信', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="comment-list">
  <% @comments.where(parent_comment_id: nil).each do |comment| %>
    <% comment_user_profile = Profile.find_by(user_id: comment.user_id) %>
    <div class="comment">
      
      <div class="header">
        <div class="header_image">
          <% if comment_user_profile.image.attached? %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag(comment_user_profile.image) %>
            <% end %>
          <% else %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          <% end %>
        </div>
        <h2 class="username"><%= comment_user_profile.nickname %></h2>
        <h2 class="timestamp">
          <% if Time.current - comment.created_at < 24.hours %>
            <%= comment.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
          <% else %>
            <%= comment.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
          <% end %>
        </h2>
        <% if comment.user_id == current_user.id %>
          <div class="dropdown">
            <button class="dropdown-toggle">・・・</button>
            <div class="dropdown-menu">
              <%= link_to "削除", destroy_comment_path(comment), method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="body">
        <p class="content auto-change-url"><%= comment.content %></p>
      </div>

      <div class="comment-footer">
        <!-- コメントボタン -->
        <a href="<%= new_reply_comment_path(@post, comment) %>", class="icon">
          <%= image_tag("comment.png", alt: "Comment Icon", class: "icon") %>
          <span class="count"><%= Comment.where(parent_comment_id: comment.id).count %></span>
        </a>
        <!-- 返信ボタン -->
        <span class="ReplyButton">返信</span>
      </div>
    </div>

    <!-- 返信フォーム -->
    <div class="comment-reply-form-container ReplyForm" data-comment-id="<%= comment.id %>">
      <%= form_with(url: create_reply_comment_path(@post, comment), model: @comment, local: true, method: :post) do |f| %>

        <% if @comment.errors.any? %>
          <ul class="error-messages">
            <% @comment.errors.full_messages.each do |message| %>
              <li>・<%= message %></li>
            <% end %> </ul>
        <% end %>

        <div class="form">
          <div class="textarea">
            <%= f.label "返信コメント", class: 'form-label' %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>

          <div class="button-group">
            <%= f.submit '送信', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- 返信フォーム -->
<script>
  function initializeReplyForms() {
    // すべての返信フォームを最初に非表示にする
    document.querySelectorAll(".ReplyForm").forEach((form) => {
      form.style.display = "none";
    });
  }

  // クリックイベントリスナーの登録（1回だけ実行）
  document.addEventListener("click", function (event) {
    if (event.target.classList.contains("ReplyButton")) {
      const commentElement = event.target.closest(".comment");
      const replyForm = commentElement.nextElementSibling; // 返信フォームは直後の要素

      if (replyForm && replyForm.classList.contains("ReplyForm")) {
        // フォームの表示/非表示を切り替え
        replyForm.style.display = replyForm.style.display === "block" ? "none" : "block";
      }
    }
  });

  // Turboで動作するようにする
  document.addEventListener("turbo:load", initializeReplyForms);
  // 直接ページロード用（Turbo未使用時の保険）
  document.addEventListener("DOMContentLoaded", initializeReplyForms);
</script>

app/views/comments/new_reply.html.erb
<div class="post-list">
  <div class="post">
    <div class="header">
      <div class="header_image">
        <% if @profile.image.attached? %>
          <%= link_to show_profile_path(@profile.user_id) do %>
            <%= image_tag(@profile.image) %>
          <% end %>
        <% else %>
          <%= link_to show_profile_path(@profile.user_id) do %>
            <%= image_tag 'no_image.png' %>
          <% end %>
        <% end %>
      </div>
      <h2 class="username"><%= @profile.nickname %></h2>
      <h2 class="category"><%= @post.category %></h2>
      <h2 class="timestamp">
        <% if Time.current - @post.created_at < 24.hours %>
          <%= @post.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
        <% else %>
          <%= @post.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
        <% end %>
      </h2>
    </div>
    <div class="body">
      <p class="content auto-change-url"><%= @post.body %></p>
    </div>
    <div class="media">
      <% if @post.media.attached? %>
        <% if @post.media.content_type.start_with?('image/') %>
          <%= image_tag(@post.media, alt: "Posted image", class: "img") %>
        <% elsif @post.media.content_type.start_with?('video/') %>
          <video controls class="video" poster="<%= url_for(@post.video_thumbnail) %>">
            <source src="<%= url_for(@post.media) %>" type="<%= @post.media.content_type %>">
            お使いのブラウザは動画タグをサポートしていません。
          </video>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="comment-list">
  <% @past_comments.each do |comment| %>
    <% comment_user_profile = Profile.find_by(user_id: comment.user_id) %>
    <div class="comment">

      <div class="header">
        <div class="header_image">
          <% if comment_user_profile.image.attached? %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag(comment_user_profile.image) %>
            <% end %>
          <% else %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          <% end %>
        </div>
        <h2 class="username"><%= comment_user_profile.nickname %></h2>
        <h2 class="timestamp">
          <% if Time.current - comment.created_at < 24.hours %>
            <%= comment.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
          <% else %>
            <%= comment.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
          <% end %>
        </h2>
        <% if comment.user_id == current_user.id %>
          <div class="dropdown">
            <button class="dropdown-toggle">・・・</button>
            <div class="dropdown-menu">
              <%= link_to "削除", destroy_comment_path(comment), method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
            </div>
          </div>
        <% end %>
      </div>
      
      <div class="body">
        <p class="content auto-change-url"><%= comment.content %></p>
      </div>

    </div>
  <% end %>

  <% @comments.each do |comment| %>
    <% comment_user_profile = Profile.find_by(user_id: comment.user_id) %>
    <div class="comment">

      <div class="header">
        <div class="header_image">
          <% if comment_user_profile.image.attached? %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag(comment_user_profile.image) %>
            <% end %>
          <% else %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          <% end %>
        </div>
        <h2 class="username"><%= comment_user_profile.nickname %></h2>
        <h2 class="timestamp">
          <% if Time.current - comment.created_at < 24.hours %>
            <%= comment.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
          <% else %>
            <%= comment.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
          <% end %>
        </h2>
        <% if comment.user_id == current_user.id %>
          <div class="dropdown">
            <button class="dropdown-toggle">・・・</button>
            <div class="dropdown-menu">
              <%= link_to "削除", destroy_comment_path(comment), method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="body">
        <p class="content auto-change-url"><%= comment.content %></p>
      </div>

      <div class="comment-footer">
        <!-- コメントボタン -->
        <a href="<%= new_reply_comment_path(@post, comment) %>", class="icon">
          <%= image_tag("comment.png", alt: "Comment Icon", class: "icon") %>
          <span class="count" ><%= Comment.where(parent_comment_id: comment.id).count %></span>
        </a>

        <!-- 返信ボタン -->
        <span class="ReplyButton">返信</span>
      </div>
    </div>

    <!-- 返信フォーム -->
    <div class="comment-reply-form-container ReplyForm" data-comment-id="<%= comment.id %>">
      <%= form_with(url: create_reply_comment_path(@post, comment), model: @comment, local: true, method: :post) do |f| %>

        <% if @comment.errors.any? %>
          <ul class="error-messages">
            <% @comment.errors.full_messages.each do |message| %>
              <li>・<%= message %></li>
            <% end %> </ul>
        <% end %>

        <div class="form">
          <div class="textarea">
            <%= f.label "返信コメント", class: 'form-label' %>
            <%= f.text_area :content, class: 'form-control' %>
          </div>

          <div class="button-group">
            <%= f.submit '送信', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- 返信フォーム -->
<script>
  function initializeReplyForms() {
    // すべての返信フォームを最初に非表示にする
    document.querySelectorAll(".ReplyForm").forEach((form) => {
      form.style.display = "none";
    });
  }

  // クリックイベントリスナーの登録（1回だけ実行）
  document.addEventListener("click", function (event) {
    if (event.target.classList.contains("ReplyButton")) {
      const commentElement = event.target.closest(".comment");
      const replyForm = commentElement.nextElementSibling; // 返信フォームは直後の要素

      if (replyForm && replyForm.classList.contains("ReplyForm")) {
        // フォームの表示/非表示を切り替え
        replyForm.style.display = replyForm.style.display === "block" ? "none" : "block";
      }
    }
  });

  // Turboで動作するようにする
  document.addEventListener("turbo:load", initializeReplyForms);
  // 直接ページロード用（Turbo未使用時の保険）
  document.addEventListener("DOMContentLoaded", initializeReplyForms);
</script>

app/views/comments/relevant.html.erb
<div class="comment-list">
  <% @comments.each_with_index do |comment, i| %>
    <% comment_user_profile = @comment_user_profiles[i] %>
    <div class="comment">
      <div class="header">
        <div class="header_image">
          <% if comment_user_profile.image.attached? %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag(comment_user_profile.image) %>
            <% end %>
          <% else %>
            <%= link_to show_profile_path(comment_user_profile.user_id) do %>
              <%= image_tag 'no_image.png' %>
            <% end %>
          <% end %>
        </div>
        <h2 class="username"><%= comment_user_profile.nickname %></h2>
        <h2 class="timestamp">
          <% if Time.current - comment.created_at < 24.hours %>
            <%= comment.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
          <% else %>
            <%= comment.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
          <% end %>
        </h2>
        <% if comment.user_id == current_user.id %>
          <div class="dropdown">
            <button class="dropdown-toggle">・・・</button>
            <div class="dropdown-menu">
              <%= link_to "削除", destroy_comment_path(comment), method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="body">
        <p class="content auto-change-url"><%= comment.content %></p>
      </div>

      <div class="comment-footer">
        <% if comment.parent_comment_id %>
          <a href="<%= new_reply_comment_path(comment.post_id, comment.parent_comment_id) %>", class="a-RelevantReplySource">
            <span class="RelevantReplySource">返信</span>
          </a>
        <% else %>
          <a href="<%= new_comment_path(comment.post_id, 1) %>", class="a-RelevantReplySource">
            <span class="RelevantReplySource">返信</span>
          </a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>