config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # devise
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations', # edit_user_registration_path
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    unlocks:       'users/unlocks'
  }

  devise_for :admins, controllers: {
    confirmations: 'admins/confirmations',
    registrations: 'admins/registrations', # edit_admin_registration_path
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    unlocks:       'admins/unlocks'
  }
  
  # home
  get '/', to: 'homes#index', as: 'index_home'
  get 'homes/policy', to: 'homes#policy', as: 'policy_home'
  get 'homes/terms', to: 'homes#terms', as: 'terms_home'
  get 'homes/tokushoho', to: 'homes#tokushoho', as: 'tokushoho_home'
  get 'homes/how_to_use', to: 'homes#how_to_use', as: 'how_to_use_home'

  # post
  get 'posts/index', to: 'posts#index', as: 'index_post'
  get 'posts/new', to: 'posts#new', as: 'new_post'
  post 'posts/new', to: 'posts#create', as: 'create_post'
  get 'posts/show/:post_id', to: 'posts#show', as: 'show_post'
  get 'posts/edit/:post_id', to: 'posts#edit', as: 'edit_post'
  post 'posts/edit/:post_id', to: 'posts#update', as: 'update_post'
  delete 'posts/destroy/:post_id', to: 'posts#destroy', as: 'destroy_post'

  # profile
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles/new', to: 'profiles#create', as: 'create_profile'
  get 'profiles/show/:user_id', to: 'profiles#show', as: 'show_profile'
  get 'profiles/edit', to: 'profiles#edit', as: 'edit_profile'
  post 'profiles/edit', to: 'profiles#update', as: 'update_profile'

  # comment
  get 'posts/show/:post_id/comments/new/:id', to: 'comments#new', as: 'new_comment'
  post 'posts/show/:post_id/comments/new', to: 'comments#create', as: 'create_comment'
  get 'posts/show/:post_id/comments/new_reply/:comment_id', to: 'comments#new_reply', as: 'new_reply_comment'
  post 'posts/show/:post_id/comments/new_reply/:comment_id', to: 'comments#create_reply', as: 'create_reply_comment'
  get 'comments/relevant', to: 'comments#load_relevant_comments', as: 'load_relevant_comment'
  delete 'comments/destroy/:comment_id', to: 'comments#destroy', as: 'destroy_comment'

  # like  
  post 'posts/:post_id/likes', to: 'likes#create', as: 'create_like'
  delete 'posts/:post_id/likes', to: 'likes#destroy', as: 'destroy_like'
  get 'likes/show', to: 'likes#show', as: 'show_like'

  # subscription
  get 'subscriptions/top', to: 'subscriptions#top', as: 'top_subscription'
  get 'subscriptions/new', to: 'subscriptions#new', as: 'new_subscription'
  post 'subscriptions/create_stripe_customer', to: 'subscriptions#create_stripe_customer', as: 'create_stripe_customer'
  get 'subscriptions/create_customer_portal', to: 'subscriptions#create_customer_portal', as: 'create_customer_portal'
  get 'subscriptions/payment_cancel', to: 'subscriptions#payment_cancel', as: 'payment_cancel'
  get 'subscriptions/checkout_success', to: 'subscriptions#checkout_success', as: 'checkout_success'
  get 'subscriptions/loading', to: 'subscriptions#loading', as: 'loading_subscription'
  get '/subscription_status', to: 'subscriptions#subscription_status'

  # contact
  get 'contacts/new', to: 'contacts#new', as: 'new_contact'
  post 'contacts/new', to: 'contacts#create', as: 'create_contact'

  # stripe
  post '/webhooks', to: 'webhooks#create'
  post '/checkouts', to: 'checkouts#create'

  # admin
  # user
  get 'admins/users/index', to: 'admins/users#index', as: 'index_admin_user'
  get 'admins/users/edit/:user_id', to: 'admins/users#edit', as: 'edit_admin_user'
  post 'admins/users/edit/:user_id', to: 'admins/users#update', as: 'update_admin_user'
  delete 'admins/users/destroy/:user_id', to: 'admins/users#destroy', as: 'destroy_admin_user'

  # post
  get 'admins/posts/index', to: 'admins/posts#index', as: 'index_admin_post'
  get 'admins/posts/media_index', to: 'admins/posts#media_index', as: 'media_index_admin_post'
  post 'admins/posts/media_index/:post_id', to: 'admins/posts#compress_media', as: 'compress_media_admin_post'
  delete 'admins/posts/destroy/:post_id', to: 'admins/posts#destroy', as: 'destroy_admin_post'

  # profile
  get 'admins/profiles/index', to: 'admins/profiles#index', as: 'index_admin_profile'
  get 'admins/profiles/media_index', to: 'admins/profiles#media_index', as: 'media_index_admin_profile'
  post 'admins/profiles/media_index/:profile_id', to: 'admins/profiles#compress_media', as: 'compress_media_admin_profile'
  delete 'admins/profiles/destroy/:profile_id', to: 'admins/profiles#destroy', as: 'destroy_admin_profile'

  # comment
  get 'admins/comments/index', to: 'admins/comments#index', as: 'index_admin_comment'
  delete 'admins/comments/destroy/:comment_id', to: 'admins/comments#destroy', as: 'destroy_admin_comment'

  # subscription
  get 'admins/subscriptions/index', to: 'admins/subscriptions#index', as: 'index_admin_subscription'
  get 'admins/subscriptions/edit/:subscription_id', to: 'admins/subscriptions#edit', as: 'edit_admin_subscription'
  post 'admins/subscriptions/edit/:subscription_id', to: 'admins/subscriptions#update', as: 'update_admin_subscription'
  delete 'admins/subscriptions/destroy/:subscription_id', to: 'admins/subscriptions#destroy', as: 'destroy_admin_subscription'

  # dashboard
  get 'admins/dashboards/index', to: 'admins/dashboards#index', as: 'index_admin_dashboard'

  # analytics
  get 'admins/analytics/index', to: 'admins/analytics#index', as: 'index_admin_analytics'

  # Sidekiq Web UI
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :profile

  validates :category, presence: true
  validates :title, presence: true
  validates :body, presence: true
  # validates :tag, presence: true
  validates :media, size: { less_than: 20.megabytes }

  has_one_attached :media, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_save :convert_video_async, if: -> { media.attached? && video? && valid_media?}
  after_save :convert_image_async, if: -> { media.attached? && image? && valid_media?}

  before_destroy :purge_media
  
  # 選択肢
  enum category: { 撮り鉄: 1, 乗り鉄: 2, 音鉄:3, 車両鉄:4, 模型鉄:5, 時刻表鉄:6, 葬式鉄:7, 廃線鉄:8, 歴史鉄:9, 駅鉄:10, 駅弁鉄:11, 線路鉄:12, 設備鉄:13, 運転鉄:14, 保安鉄:15, ママ鉄:16, 架空鉄:17, 配線鉄:18, ゲーム鉄:19, 雑談:99}

  # ファイルが動画かどうか判定
  def video?
    return false unless media.attached?
    media.content_type.start_with?("video/")
  end

  # ファイルが画像かどうか判定
  def image?
    return false unless media.attached?
    media.content_type.start_with?("image/")
  end

  # ファイル名にcompressedが含まれているか判定
  def valid_media?
    return false unless media.attached?
    filename = media.filename.to_s
    !filename.include?('compressed')
  end

  # postを削除する際、S3に保存されたmediaも削除する
  def purge_media
    media.purge if media.attached?
  end

  # 動画のサムネイルを作成（ffmpeg必要）
  def video_thumbnail
    return unless media.content_type.start_with?("video/")
    media.representation(resize_to_limit: [1280, 720]).processed
  end

  # # 未圧縮の画像・動画を取得するメソッド
  # def self.uncompressed_videos
  #   joins(media_attachment: :blob)
  #     .where.not("active_storage_blobs.filename LIKE ?", "%compressed%")
  # end

  private

  # 非同期で動画を変換 & 圧縮
  def convert_video_async
    VideoCompressionJob.perform_later(id)
  end

  # 非同期で画像を変換 & 圧縮
  def convert_image_async
    PostImageCompressionJob.perform_later(id)
  end

end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
	before_action :authenticate_admin!
	
	def index
    @posts = Post.all
  end

	def destroy
    @post = Post.find(params[:post_id])
    @post.destroy
    redirect_to index_admin_post_path, notice: '投稿を削除しました。'
  end

  def media_index
    @posts = Post.with_attached_media
  end

  def compress_media
    @post = Post.find(params[:post_id])
    if @post.media.attached? &&  @post.media.content_type.start_with?('video/')
      VideoCompressionJob.perform_later(@post.id) # 圧縮処理を非同期で実行
      redirect_to media_index_admin_post_path, notice: '動画の圧縮処理を実行しました'
    elsif @post.media.attached? &&  @post.media.content_type.start_with?('image/')
      PostImageCompressionJob.perform_later(@post.id) # 圧縮処理を非同期で実行
      redirect_to media_index_admin_post_path, notice: '画像の圧縮処理を実行しました'
    else
      redirect_to media_index_admin_post_path, alert: 'メディアがありません'
    end
  end

  private

  def authenticate_admin!
    unless current_user&.admin?
      redirect_to index_post_path, alert: '管理者のみがアクセスできます。'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_subscription_status

  def index
    title = params[:title]
    category = params[:category]
    if title.present?
      @posts = Post.where('title LIKE ?', "%#{title}%")
    elsif category.present?
      @posts = Post.where('category LIKE ?', "%#{category}%")
      @category = Post.new
      @category.category = params[:category].to_i
    else
      @posts = Post.all
    end
    @posts = @posts.order(created_at: :desc)
    # ページネーションを追加 (100件ずつ表示)
    @posts = @posts.page(params[:page]).per(100) # 100件ずつ
    @profiles = @posts.map(&:profile)
    # 投稿毎のコメント数の算出
    @comment_count = []
    @posts.each do |post|
      @comments = Comment.where(post_id: post.id)
      @comment_count << @comments.count
    end
    #非同期リクエストに対応
    respond_to do |format|
      format.html # 初回ロード
      format.js   # "もっと読み込む" ボタンのクリック時
    end
    # render :index
  end
  
  def new
    @post = Post.new
    render :new
  end
  
  def create
    @post = Post.new(post_params)
    @profile = Profile.find_by(user_id: current_user.id)
    @post.profile_id = @profile.id
    if params[:post][:media]
      @post.media.attach(params[:post][:media])
    end
    if @post.save
      redirect_to index_post_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    render :edit
  end

  def update
    @post = Post.find(params[:post_id])
    if params[:post][:media]
      @post.media.purge
      @post.media.attach(params[:post][:media])
    end
    if @post.update(post_params)
      redirect_to show_profile_path(current_user.id), notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.destroy
    redirect_to show_profile_path(current_user.id), notice: '削除しました'
  end

  private
  def post_params
    params.require(:post).permit(:category, :title, :body, :tag, :media).merge(user_id: current_user.id)
  end

end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post">

  <div class="header">
    <div class="header_image">
      <% if profile.image.attached? %>
        <%= link_to show_profile_path(profile.user_id) do %>
          <%= image_tag(profile.image) %>
        <% end %>
      <% else %>
        <%= link_to show_profile_path(profile.user_id) do %>
          <%= image_tag 'no_image.png' %>
        <% end %>
      <% end %>
    </div>
    <h2 class="username"><%= profile.nickname %></h2>
    <h2 class="category"><%= post.category %></h2>
    <h2 class="timestamp">
      <% if Time.current - post.created_at < 24.hours %>
        <%= post.created_at.strftime("%H:%M") %> <!-- 24時間未満なら時間のみ -->
      <% else %>
        <%= post.created_at.strftime("%Y/%m/%d") %> <!-- 24時間以上なら日付のみ -->
      <% end %>
    </h2> 
    <% if post.user_id == current_user.id %>
      <div class="dropdown">
        <button class="dropdown-toggle">・・・</button>
        <div class="dropdown-menu">
          <%= link_to "編集", edit_post_path(post), class: "dropdown-item" %>
          <%= link_to "削除", destroy_post_path(post), method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
        </div>
      </div>
    <% end %>
  </div>

  <h2 class="title"><%= post.title %></h2>
  <div class="body">
    <p class="content auto-change-url"><%= post.body %></p>
  </div>

  <div class="media">
    <% if post.media.attached? %>
      <% if post.media.content_type.start_with?('image/') %>
        <%= image_tag(post.media, alt: "Posted image", class: "img") %>
      <% elsif post.media.content_type.start_with?('video/') %>
        <video controls class="video" poster="<%= url_for(post.video_thumbnail) %>">
          <source src="<%= url_for(post.media) %>" type="<%= post.media.content_type %>">
          お使いのブラウザは動画タグをサポートしていません。
        </video>
      <% end %>
    <% end %>
  </div>
  
  <div class="post-footer">
    <!-- いいねボタン -->
    <div id="like_buttons_<%= post.id %>">
      <%= render "likes/like", post: post %>
    </div>
    <!-- コメントボタン -->
    <a href="<%= new_comment_path(post, 0) %>", class="icon">
      <%= image_tag("comment.png", alt: "Comment Icon", class: "icon") %>
      <span class="count" ><%= comment_count %></span>
    </a>
  </div>
  
</div>

app/views/posts/_posts.html.erb
<% posts.each_with_index do |post, i| %>
  <%= render partial: "post", locals: { post: post, profile: profiles[i], comment_count: comment_count[i] } %>
<% end %>

app/views/posts/edit.html.erb
<div class="post-container">
  <div class="post-form-container">
    <h2 class="h2">投稿を編集してください</h2>
    <%= form_with(url: update_post_path, model: @post, local: true, method: :post, html: { class: 'post-form' }) do |f| %>

      <% if @post.errors.any? %>
        <ul class="error-messages">
          <% @post.errors.full_messages.each do |message| %>
            <li>・<%= message %></li>
          <% end %> </ul>
      <% end %>

      <div class="form-group">
        <%= f.label :category, class: 'form-label'  %>
        <%= f.select :category, options_for_select(Post.categories.keys.map { |k| [k.humanize, k] }, @post.category), {include_blank: "選択してください"}, {class: "form-control-narrow-width"} %>
      </div>

      <div class="form-group">
        <%= f.label :title, class: 'form-label' %>
        <%= f.text_field :title, value: @post.title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body, class: 'form-label' %>
        <%= f.text_area :body, value: @post.body, class: 'form-text-area' %>
      </div>

      <div class="media-upload">
        <%= f.label :media, "画像または動画をアップロード（アスペクト比16:9推奨、20MB以下）", class: 'form-label' %>
        <div class="media-preview" id="mediaPreview">
          <% if @post.media.attached? %>
            <% if @post.media.content_type.start_with?('image/') %>
              <img src="<%= url_for(@post.media) %>" alt="Image Preview" class="media-preview__image -block">
            <% elsif @post.media.content_type.start_with?('video/') %>
              <video controls class="media-preview__video -block">
                <source src="<%= url_for(@post.media) %>" type="<%= @post.media.content_type %>">
                お使いのブラウザは動画タグをサポートしていません。
              </video>
            <% end %>
            <span class="media-preview__default-text -none">No media uploaded</span>
          <% else %>
            <img src="" alt="Image Preview" class="media-preview__image">
            <video controls class="media-preview__video" style="display: none;"></video>
            <span class="media-preview__default-text">No media uploaded</span>
          <% end %>
        </div>
        <%= f.file_field :media, class: 'form-control-file', id: 'mediaUpload', accept: "image/*,video/*" %>
      </div>

      <p>※画像から動画、もしくは動画から画像に変更する場合、プレビュー画面は変化しませんが変更は反映されます。</p>

      <!--
      <div class="form-group">
        <%= f.label :tag, class: 'form-label' %>
        <%= f.text_field :tag, value: @post.tag, class: 'form-control' %>
      </div>
      -->

      <div class="button-group">
        <%= link_to '削除', destroy_post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>
        <%= f.submit '更新', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="search-container">
  <%= form_with url: index_post_path, class: "form", method: :get, local: true do |form| %>
    <input class="input" type="text" name="title" placeholder="タイトルで検索" value="<%= params[:title] %>">
    <%= form.submit "検索", class: "button" %>
  <% end %>
</div>

<% if @category %>
  <div class="category-container">
    <div class="category">
      <h3><%= @category.category%></h3>
    </div>
  </div>
<% end %>

<div class="post-list">
  <% @posts.each_with_index do |post, i| %>
    <%= render partial: "post", locals: { post: post, profile: @profiles[i], comment_count: @comment_count[i] } %>
  <% end %>
</div>

<div class="load-more-container">
  <% if @posts.next_page %>
    <button id="load-more-button" data-next-page="<%= @posts.next_page %>">
      もっと読み込む
    </button>
  <% end %>
</div>

<!-- 100投稿ずつ表示する -->
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const loadMoreButton = document.getElementById("load-more-button");

    if (loadMoreButton) {
      loadMoreButton.addEventListener("click", async () => {
        const nextPage = loadMoreButton.dataset.nextPage;
        
        // 現在の検索条件を取得
        const params = new URLSearchParams(window.location.search);
        params.set("page", nextPage); // 次のページを設定

        const url = `${window.location.pathname}?${params.toString()}`;

        try {
          const response = await fetch(url, {
            headers: { 
              "X-Requested-With": "XMLHttpRequest", // Ajaxリクエストを明示
              "Accept": "text/javascript", // JavaScriptレスポンスを期待
            },
          });

          if (!response.ok) throw new Error("ネットワークエラー");

          const script = await response.text();
          eval(script); // サーバーから送られたJavaScriptを実行

        } catch (error) {
          console.error("エラーが発生しました:", error);
        }
      });
    }
  });
</script>

app/views/posts/index.js.erb
// `post-list` に新しい投稿を追加
document.querySelector(".post-list").insertAdjacentHTML("beforeend", "<%= j(render partial: 'posts/posts', locals: { posts: @posts, profiles: @profiles, comment_count: @comment_count }) %>");

// 次のページがあればボタンの `data-next-page` を更新し、なければ削除
const loadMoreButton = document.getElementById("load-more-button");

<% if @posts.next_page %>
  loadMoreButton.dataset.nextPage = "<%= @posts.next_page %>";
<% else %>
  loadMoreButton.remove();
<% end %>

app/views/posts/new.html.erb
<div class="post-container">
  <div class="post-form-container">
    <h2 class="h2">新規投稿</h2>
    
    <%= form_with(url: create_post_path, model: @post, local: true, method: :post, html: { class: 'post-form' } ) do |f| %>

      <% if @post.errors.any? %>
        <ul class="error-messages">
          <% @post.errors.full_messages.each do |message| %>
            <li>・<%= message %></li>
          <% end %> </ul>
      <% end %>

      <div class="form-group">
        <%= f.label :category, class: 'form-label'  %>
        <%= f.select :category, Post.categories.keys.map { |k| [k.humanize, k] }, { include_blank: "選択してください" }, { class: "form-control-narrow-width" } %>
      </div>

      <div class="form-group">
        <%= f.label :title, class: 'form-label' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body, class: 'form-label' %>
        <%= f.text_area :body, class: 'form-text-area' %>
      </div>

      <div class="media-upload">
        <%= f.label :media, "画像または動画をアップロード（アスペクト比16:9推奨、20MB以下）", class: 'form-label' %>
        <div class="media-preview" id="mediaPreview">
          <img src="" alt="Image Preview" class="media-preview__image" style="display: none;">
          <video controls class="media-preview__video" style="display: none;"></video>
          <span class="media-preview__default-text">選択したメディアがここに表示されます</span>
        </div>
        <%= f.file_field :media, class: 'form-control-file', id: 'mediaUpload', accept: "image/*,video/*" %>
      </div>

      <!--
      <div class="form-group">
        <%= f.label :tag, class: 'form-label' %>
        <%= f.text_field :tag, class: 'form-control' %>
      </div>
      -->

      <div class="button-group">
        <%= f.submit '投稿する', class: 'btn btn-primary' %>
      </div>
    
    <% end %>
  </div>
</div>